name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco-aggregate/jacoco.csv
          badges-directory: .github/badges
          generate-coverage-badge: true
          generate-branches-badge: true
          branches-badge-filename: branches.svg
          generate-coverage-endpoint: true
          coverage-endpoint-filename: jacoco.json
          generate-branches-endpoint: true
          branches-endpoint-filename: branches.json
          generate-summary: true
          summary-filename: coverage-summary.json
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'BeytullahC'
            git config --global user.email 'beytullah.dakich@gmail.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
